services:
  - type: web
    name: symfony-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear --env=prod
    startCommand: |
      php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString
      - key: APP_SECRET
        generateValue: true

databases:
  - name: symfony-db
    plan: free
